name: Deploy

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: '0.119.0'
            
            - name: Build
              run: hugo --minify

            - name: Deploy to Staging server
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                ARGS: "-rlgoDzvc -i --delete"
                SOURCE: "public/"
                REMOTE_HOST: ${{ secrets.HOST }}
                REMOTE_USER: ${{ secrets.USER }}
                TARGET: ${{ secrets.TARGET }}
